# Generated by Django 5.2 on 2025-05-02 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('ucode', models.IntegerField()),
                ('hcode', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'flights',
            },
        ),
    ]
