# Generated by Django 5.2 on 2025-05-24 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('craftName', models.CharField(default='poop', max_length=3)),
                ('departTime', models.IntegerField()),
                ('arriveTime', models.IntegerField()),
                ('startLocation', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'flights',
            },
        ),
        migrations.CreateModel(
            name='Planes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('craftName', models.CharField(max_length=14)),
                ('passengers', models.IntegerField()),
                ('maxPassengers', models.IntegerField()),
            ],
            options={
                'db_table': 'planes',
            },
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookingRef', models.IntegerField(default=5, unique=True)),
                ('passengerID', models.IntegerField()),
                ('bookedSeats', models.IntegerField(default=0)),
                ('flightCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flightBookingAPI.flights')),
            ],
            options={
                'db_table': 'bookings',
            },
        ),
    ]
