# Generated by Django 5.2 on 2025-05-07 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('craftName', models.CharField(default='poop', max_length=3)),
                ('departTime', models.IntegerField()),
                ('arriveTime', models.IntegerField()),
                ('startLocation', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'flights',
            },
        ),
    ]
