# Generated by Django 5.2 on 2025-05-24 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flightBookingAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookings',
            options={'managed': True},
        ),
    ]
