# Generated by Django 5.2 on 2025-05-07 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightBookingAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flights',
            old_name='description',
            new_name='destination',
        ),
        migrations.RenameField(
            model_name='flights',
            old_name='ucode',
            new_name='maxBookings',
        ),
        migrations.RemoveField(
            model_name='flights',
            name='hcode',
        ),
        migrations.AddField(
            model_name='flights',
            name='bookedSeats',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flights',
            name='craftName',
            field=models.CharField(default='poop', max_length=3, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='flights',
            name='startLocation',
            field=models.CharField(default='stuff', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flights',
            name='code',
            field=models.IntegerField(),
        ),
    ]
