# Generated by Django 5.2 on 2025-05-24 04:42

import flightBookingAPI.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightBookingAPI', '0002_alter_bookings_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='bookedSeats',
        ),
        migrations.RemoveField(
            model_name='planes',
            name='id',
        ),
        migrations.RemoveField(
            model_name='planes',
            name='passengers',
        ),
        migrations.AddField(
            model_name='flights',
            name='passengers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='bookingRef',
            field=models.IntegerField(default=flightBookingAPI.models.uniqueGenerator, unique=True),
        ),
        migrations.AlterField(
            model_name='planes',
            name='craftName',
            field=models.CharField(max_length=14, primary_key=True, serialize=False),
        ),
    ]
