# Generated by Django 5.2 on 2025-05-07 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightBookingAPI', '0002_rename_description_flights_destination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flights',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='flights',
            name='craftName',
            field=models.CharField(default='poop', max_length=3),
        ),
    ]
