# Generated by Django 5.2 on 2025-05-24 04:50

import flightBookingAPI.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightBookingAPI', '0003_remove_bookings_bookedseats_remove_planes_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='id',
        ),
        migrations.AlterField(
            model_name='bookings',
            name='bookingRef',
            field=models.IntegerField(default=flightBookingAPI.models.uniqueGenerator, primary_key=True, serialize=False, unique=True),
        ),
    ]
