# Generated by Django 5.2 on 2025-05-07 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightBookingAPI', '0003_flights_id_alter_flights_craftname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flights',
            name='id',
        ),
        migrations.AlterField(
            model_name='flights',
            name='code',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
