# Generated by Django 5.2 on 2025-05-24 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightBookingAPI', '0004_remove_bookings_id_alter_bookings_bookingref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planes',
            name='craftName',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
