# Generated by Django 5.2 on 2025-05-24 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightBookingAPI', '0005_alter_planes_craftname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flights',
            name='arriveTime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='flights',
            name='departTime',
            field=models.DateTimeField(),
        ),
    ]
