# Generated by Django 5.2 on 2025-05-24 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightBookingAPI', '0006_alter_flights_arrivetime_alter_flights_departtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airportCode', models.CharField(max_length=4)),
            ],
            options={
                'db_table': 'airports',
            },
        ),
    ]
