# Generated by Django 5.2 on 2025-05-24 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightBookingAPI', '0007_airports'),
    ]

    operations = [
        migrations.AddField(
            model_name='airports',
            name='name',
            field=models.CharField(default='', max_length=25),
        ),
    ]
