# Generated by Django 5.2 on 2025-05-24 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightBookingAPI', '0008_airports_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='passengerID',
            field=models.CharField(max_length=255),
        ),
    ]
