# Generated by Django 5.2 on 2025-05-28 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightBookingAPI', '0009_alter_bookings_passengerid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flights',
            name='craftName',
            field=models.CharField(max_length=3),
        ),
    ]
