# Generated by Django 5.2 on 2025-05-28 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightBookingAPI', '0010_alter_flights_craftname'),
    ]

    operations = [
        migrations.AddField(
            model_name='flights',
            name='price',
            field=models.IntegerField(default=9999),
        ),
    ]
